import { RPCsRecord } from '../types';

export const PUBLIC_RPCS: RPCsRecord = {
  blast: [
    'https://rpc.ankr.com/blast',
    // 'https://blast.blockpi.network/v1/rpc/public',
    // 'https://rpc.envelop.is/blast',
    // 'https://rpc.blast.io',
  ],

  bsc: [
    // 'https://binance.llamarpc.com',
    // 'https://bsc-pokt.nodies.app',
    // 'https://bsc.blockpi.network/v1/rpc/public',
    // 'https://bsc-mainnet.public.blastapi.io',
    // 'https://1rpc.io/bnb',
    // 'https://bsc.publicnode.com',
    // 'https://bsc.meowrpc.com',
    // 'https://bsc.drpc.org',
    // 'https://endpoints.omniatech.io/v1/bsc/mainnet/public',
    'https://rpc.ankr.com/bsc',
  ],
  opBNB: [
    // 'https://opbnb.publicnode.com',
    // 'https://opbnb-mainnet.nodereal.io/v1/64a9df0874fb4a93b9d0a3849de012d3',
    // 'https://opbnb-mainnet.nodereal.io/v1/e9a36765eb8a40b9bd12e680a1fd2bc5',
    // 'https://1rpc.io/opbnb',
    'https://opbnb-mainnet-rpc.bnbchain.org',
  ],
  eth: [
    // 'https://eth.llamarpc.com',
    // 'https://eth-pokt.nodies.app',
    // 'https://ethereum.blockpi.network/v1/rpc/public',
    // 'https://eth-mainnet.public.blastapi.io',
    // 'https://1rpc.io/eth',
    // 'https://ethereum.publicnode.com',
    // 'https://eth.meowrpc.com',
    // 'https://eth.drpc.org',
    // 'https://endpoints.omniatech.io/v1/eth/mainnet/public',
    // 'https://eth.merkle.io',
    'https://rpc.ankr.com/eth',
  ],

  polygon: [
    // 'https://polygon.llamarpc.com',
    // 'https://polygon-pokt.nodies.app',
    // 'https://polygon.blockpi.network/v1/rpc/public',
    // 'https://polygon-mainnet.public.blastapi.io',
    'https://1rpc.io/matic',
    // 'https://polygon-bor.publicnode.com',
    // 'https://polygon.meowrpc.com',
    // 'https://polygon.drpc.org',
    // 'https://endpoints.omniatech.io/v1/matic/mainnet/public',
    // 'https://polygon-rpc.com',
    'https://rpc.ankr.com/polygon',
  ],
  avalanche: [
    // 'https://avax-pokt.nodies.app/ext/bc/C/rpc',
    // 'https://avalanche.blockpi.network/v1/rpc/public',
    // 'https://ava-mainnet.public.blastapi.io/ext/bc/C/rpc',
    // 'https://1rpc.io/avax/c',
    // 'https://avalanche-c-chain.publicnode.com',
    // 'https://avax.meowrpc.com',
    // 'https://avalanche.drpc.org',
    // 'https://endpoints.omniatech.io/v1/avax/mainnet/public',
    // 'https://avalanche.public-rpc.com',
    'https://rpc.ankr.com/avalanche',
  ],
  arbitrum: [
    // 'https://arbitrum.llamarpc.com',
    // 'https://arb-pokt.nodies.app',
    // 'https://arbitrum.blockpi.network/v1/rpc/public',
    'https://arbitrum-one.public.blastapi.io',
    // 'https://1rpc.io/arb',
    // 'https://arbitrum-one.publicnode.com',
    // 'https://arbitrum.meowrpc.com',
    // 'https://arbitrum.drpc.org',
    // 'https://endpoints.omniatech.io/v1/arbitrum/one/public',
    // 'https://arb1.arbitrum.io/rpc',
    // 'https://rpc.ankr.com/arbitrum',
  ],
  optimism: [
    // 'https://optimism.llamarpc.com',
    // 'https://op-pokt.nodies.app',
    // 'https://optimism.blockpi.network/v1/rpc/public',
    // 'https://optimism-mainnet.public.blastapi.io',
    // 'https://1rpc.io/op',
    // 'https://optimism.publicnode.com',
    // 'https://optimism.meowrpc.com',
    // 'https://optimism.drpc.org',
    // 'https://endpoints.omniatech.io/v1/op/mainnet/public',
    // 'https://mainnet.optimism.io',
    'https://rpc.ankr.com/optimism',
  ],

  zkSync: [
    // 'https://zksync-era.blockpi.network/v1/rpc/public',
    // 'https://1rpc.io/zksync2-era',
    // 'https://zksync.meowrpc.com',
    // 'https://zksync.drpc.org',
    'https://mainnet.era.zksync.io',
  ],
  zkFair: ['https://rpc.zkfair.io'],
  polygon_zkevm: [
    'https://polygon-zkevm.blockpi.network/v1/rpc/public',
    'https://polygon-zkevm-mainnet.public.blastapi.io',
    'https://1rpc.io/polygon/zkevm',
    'https://polygon-zkevm.drpc.org',
    'https://zkevm-rpc.com',
    'https://rpc.ankr.com/polygon_zkevm',
  ],

  base: [
    // 'https://base.llamarpc.com',
    // 'https://base-pokt.nodies.app',
    // 'https://base.blockpi.network/v1/rpc/public',
    // 'https://base-mainnet.public.blastapi.io',
    // 'https://1rpc.io/base',
    // 'https://base.publicnode.com',
    // 'https://base.meowrpc.com',
    // 'https://base.drpc.org',
    // 'https://endpoints.omniatech.io/v1/base/mainnet/public',
    // 'https://rpc.gnosischain.com',
    'https://rpc.ankr.com/base',
  ],
  linea: [
    'https://linea.blockpi.network/v1/rpc/public',
    'https://1rpc.io/linea',
    'https://linea.drpc.org',
    'https://rpc.linea.build',
  ],
  scroll: [
    // 'https://scroll.blockpi.network/v1/rpc/public',
    'https://scroll-mainnet.public.blastapi.io',
    // 'https://1rpc.io/scroll',
    // 'https://rpc.scroll.io',
    // 'https://rpc-scroll.icecreamswap.com',
    // 'https://rpc.ankr.com/scroll',
  ],
  fantom: [
    'https://fantom-pokt.nodies.app',
    'https://fantom.blockpi.network/v1/rpc/public',
    'https://fantom.publicnode.com',
    'https://fantom.drpc.org',
    'https://endpoints.omniatech.io/v1/fantom/mainnet/public',
    'https://rpcapi.fantom.network',
    'https://rpc.fantom.network',
    'https://rpc2.fantom.network',
    'https://rpc3.fantom.network',
    'https://rpc.ankr.com/fantom',
  ],

  core: [
    'https://1rpc.io/core',
    'https://rpc-core.icecreamswap.com',
    'https://rpc.coredao.org',
    'https://core.public.infstones.com',
    'https://rpc.ankr.com/core',
  ],
  celo: ['https://1rpc.io/celo', 'https://forno.celo.org', 'https://rpc.ankr.com/celo'],
  zora: ['https://rpc.zora.energy'],

  gnosis: [
    'https://gnosis-pokt.nodies.app',
    'https://gnosis.blockpi.network/v1/rpc/public',
    'https://gnosis-mainnet.public.blastapi.io',
    'https://1rpc.io/gnosis',
    'https://gnosis.publicnode.com',
    'https://gnosis.drpc.org',
    'https://endpoints.omniatech.io/v1/gnosis/mainnet/public',
    'https://rpc.ankr.com/gnosis',
  ],
  klay: [
    'https://klaytn-pokt.nodies.app',
    'https://klaytn.blockpi.network/v1/rpc/public',
    'https://1rpc.io/klay',
    'https://klaytn.drpc.org',
    'https://rpc.ankr.com/klaytn',
  ],

  aptos: ['https://rpc.ankr.com/http/aptos/v1'],
  starknet: ['https://starknet-mainnet.public.blastapi.io'],

  moonbeam: ['https://rpc.ankr.com/moonbeam'],
};
