export const RANDOM_WORDS = [
  'technology',
  'food',
  'music',
  'movie',
  'project',
  'team',
  'animal',
  'plant',
  'river',
  'mountain',
  'ocean',
  'planet',
  'universe',
  'space',
  'language',
  'culture',
  'art',
  'sport',
  'science',
  'math',
  'history',
  'fiction',
  'nature',
  'city',
  'country',
  'continent',
  'forest',
  'desert',
  'holiday',
  'event',
  'festival',
  'celebration',
  'journey',
  'adventure',
  'experience',
  'emotion',
  'feeling',
  'idea',
  'concept',
  'discovery',
  'invention',
  'health',
  'wealth',
  'happiness',
  'success',
  'failure',
  'friendship',
  'love',
  'family',
  'relationship',
  'communication',
  'travel',
  'food',
  'drink',
  'game',
  'toy',
  'tool',
  'weapon',
  'clothing',
  'shelter',
  'vehicle',
  'instrument',
  'book',
  'movie',
  'music',
  'artwork',
  'computer',
  'phone',
  'internet',
  'software',
  'hardware',
  'website',
  'social media',
  'network',
  'platform',
  'cloud',
  'data',
  'algorithm',
  'robot',
  'AI',
  'virtual reality',
  'augmented reality',
  'blockchain',
  'crypto',
  'space travel',
  'climate change',
  'environment',
  'sustainability',
  'healthcare',
  'medicine',
  'vaccine',
  'pandemic',
  'disaster',
  'accident',
  'crime',
  'politics',
  'economy',
  'education',
  'technology',
  'innovation',
  'research',
  'discovery',
  'exploration',
  'creativity',
  'curiosity',
  'imagination',
  'progress',
  'freedom',
  'justice',
  'equality',
  'peace',
  'war',
  'religion',
  'philosophy',
  'spirituality',
  'culture',
  'tradition',
  'celebration',
  'art',
  'literature',
  'history',
  'mythology',
  'legend',
  'folklore',
  'language',
  'communication',
  'relationship',
  'identity',
  'community',
  'society',
  'civilization',
  'nature',
  'ecosystem',
  'biology',
  'genetics',
  'evolution',
  'physics',
  'chemistry',
  'astronomy',
  'geology',
  'mathematics',
  'geometry',
  'algebra',
  'calculus',
  'statistics',
  'engineering',
  'architecture',
  'medicine',
  'psychology',
  'sociology',
  'economics',
  'anthropology',
  'politics',
  'geography',
  'climate',
  'oceanography',
  'meteorology',
  'law',
  'business',
  'finance',
  'marketing',
  'management',
  'leadership',
  'entrepreneurship',
  'startup',
  'education',
  'teaching',
  'learning',
  'student',
  'teacher',
  'school',
  'university',
  'college',
  'graduation',
  'career',
  'job',
  'employment',
  'work',
  'success',
  'failure',
  'goal',
  'achievement',
  'ambition',
  'motivation',
  'creativity',
  'innovation',
  'art',
  'music',
  'film',
  'literature',
  'science',
  'technology',
  'space',
  'nature',
  'environment',
  'health',
  'wellness',
  'fitness',
  'nutrition',
  'medicine',
  'therapy',
  'happiness',
  'love',
  'friendship',
  'family',
  'community',
  'society',
  'culture',
  'identity',
  'travel',
  'adventure',
  'exploration',
  'discovery',
  'learning',
  'knowledge',
  'wisdom',
  'experience',
  'memory',
  'emotion',
  'feeling',
  'thought',
  'perception',
  'consciousness',
  'dream',
  'imagination',
  'fantasy',
  'reality',
  'virtual reality',
  'history',
  'evolution',
  'revolution',
  'progress',
  'change',
  'challenge',
  'conflict',
  'resolution',
  'peace',
  'war',
  'competition',
  'cooperation',
  'victory',
  'defeat',
  'hero',
  'villain',
  'myth',
  'legend',
  'story',
  'time',
  'year',
  'people',
  'way',
  'day',
  'man',
  'government',
  'woman',
  'life',
  'child',
  'world',
  'school',
  'state',
  'family',
  'group',
  'country',
  'problem',
  'hand',
  'part',
  'place',
  'case',
  'week',
  'company',
  'system',
  'program',
  'question',
  'work',
  'government',
  'number',
  'night',
  'point',
  'home',
  'water',
  'room',
  'mother',
  'area',
  'money',
  'story',
  'fact',
  'month',
  'lot',
  'right',
  'study',
  'book',
  'eye',
  'job',
  'word',
  'business',
  'issue',
  'side',
  'kind',
  'head',
  'house',
  'service',
  'friend',
  'father',
  'power',
  'hour',
  'game',
  'line',
  'end',
  'member',
  'law',
  'car',
  'city',
  'community',
  'name',
  'president',
  'team',
  'minute',
  'idea',
  'kid',
  'body',
  'information',
  'back',
  'parent',
  'face',
  'others',
  'level',
  'office',
  'door',
  'health',
  'person',
  'art',
  'war',
  'history',
  'party',
  'result',
  'change',
  'morning',
  'reason',
  'research',
  'girl',
  'guy',
  'moment',
  'air',
  'teacher',
  'force',
  'education',
];

export const COLORS = [
  'red',
  'blue',
  'yellow',
  'green',
  'orange',
  'purple',
  'vermilion',
  'amber',
  'chartreuse',
  'teal',
  'violet',
  'magenta',
  'black',
  'white',
  'gray',
  'pink',
  'brown',
  'beige',
  'maroon',
  'navy',
  'olive',
  'lime',
  'cyan',
  'turquoise',
  'indigo',
  'lavender',
  'coral',
  'gold',
  'silver',
  'crimson',
  'burgundy',
  'salmon',
  'mint',
  'peach',
  'mustard',
  'sky blue',
  'royal blue',
  'azure',
  'aquamarine',
  'periwinkle',
  'fuchsia',
  'lilac',
  'chocolate',
  'sienna',
  'charcoal',
  'slate',
  'plum',
  'raspberry',
  'blush',
  'ecru',
  'forest green',
  'sea green',
  'sand',
  'terracotta',
  'moss green',
  'mahogany',
  'sage',
  'emerald',
  'rose',
  'wheat',
  'neon green',
  'neon pink',
  'neon orange',
  'neon yellow',
  'electric blue',
  'hot pink',
  'cerulean',
  'cobalt',
  'jade',
  'sepia',
  'taupe',
  'umber',
  'ochre',
  'vermillion',
  'titian',
];

export const PREPOSITIONS = [
  'about',
  'above',
  'across',
  'after',
  'against',
  'along',
  'among',
  'around',
  'at',
  'before',
  'behind',
  'below',
  'beneath',
  'beside',
  'between',
  'beyond',
  'but',
  'by',
  'concerning',
  'despite',
  'down',
  'during',
  'except',
  'for',
  'from',
  'in',
  'inside',
  'into',
  'like',
  'near',
  'of',
  'off',
  'on',
  'onto',
  'out',
  'outside',
  'over',
  'past',
  'regarding',
  'since',
  'through',
  'throughout',
  'to',
  'toward',
  'under',
  'underneath',
  'until',
  'up',
  'upon',
  'with',
  'within',
  'without',
];

export const BODY_PARTS = [
  'head',
  'hair',
  'forehead',
  'eyebrow',
  'eye',
  'eyelash',
  'ear',
  'nose',
  'nostril',
  'mouth',
  'lip',
  'tooth',
  'tongue',
  'cheek',
  'chin',
  'jaw',
  'neck',
  'shoulder',
  'arm',
  'elbow',
  'wrist',
  'hand',
  'palm',
  'finger',
  'thumb',
  'nail',
  'chest',
  'breast',
  'abdomen',
  'stomach',
  'waist',
  'hip',
  'back',
  'spine',
  'buttock',
  'leg',
  'thigh',
  'knee',
  'calf',
  'ankle',
  'foot',
  'heel',
  'toe',
  'skin',
  'muscle',
  'bone',
  'vein',
  'artery',
  'heart',
  'lung',
  'brain',
  'liver',
  'kidney',
  'intestine',
  'bladder',
  'esophagus',
  'pancreas',
  'spleen',
];

export const ANIMALS = [
  'aardvark',
  'alligator',
  'alpaca',
  'ant',
  'anteater',
  'antelope',
  'ape',
  'armadillo',
  'baboon',
  'badger',
  'bat',
  'bear',
  'beaver',
  'bee',
  'bison',
  'boar',
  'buffalo',
  'butterfly',
  'camel',
  'caribou',
  'cat',
  'caterpillar',
  'cattle',
  'chameleon',
  'cheetah',
  'chicken',
  'chimpanzee',
  'chinchilla',
  'clam',
  'cobra',
  'cockroach',
  'cod',
  'coyote',
  'crab',
  'crane',
  'crocodile',
  'crow',
  'deer',
  'dinosaur',
  'dog',
  'dolphin',
  'donkey',
  'dove',
  'dragonfly',
  'duck',
  'eagle',
  'eel',
  'elephant',
  'elk',
  'emu',
  'falcon',
  'ferret',
  'fish',
  'flamingo',
  'fly',
  'fox',
  'frog',
  'gazelle',
  'gerbil',
  'giraffe',
  'goat',
  'goose',
  'gorilla',
  'grasshopper',
  'guinea pig',
  'hamster',
  'hare',
  'hawk',
  'hedgehog',
  'hippopotamus',
  'hornet',
  'horse',
  'hummingbird',
  'hyena',
  'ibex',
  'iguana',
  'impala',
  'jackal',
  'jaguar',
  'jellyfish',
  'kangaroo',
  'koala',
  'komodo dragon',
  'krill',
  'ladybug',
  'lemur',
  'leopard',
  'lion',
  'lizard',
  'llama',
  'lobster',
  'lynx',
  'macaw',
  'mole',
  'monkey',
  'moose',
  'mosquito',
  'mouse',
  'mule',
  'narwhal',
  'newt',
  'octopus',
  'opossum',
  'ostrich',
  'otter',
  'owl',
  'ox',
  'panda',
  'panther',
  'parrot',
  'peacock',
  'pelican',
  'penguin',
  'pheasant',
  'pig',
  'pigeon',
  'platypus',
  'polar bear',
  'porcupine',
  'possum',
  'prairie dog',
  'prawn',
  'python',
  'rabbit',
  'raccoon',
  'rat',
  'raven',
  'reindeer',
  'rhinoceros',
  'robin',
  'salamander',
  'salmon',
  'scorpion',
  'seahorse',
  'seal',
  'shark',
  'sheep',
  'shrimp',
  'skunk',
  'sloth',
  'snail',
  'snake',
  'sparrow',
  'spider',
  'squid',
  'squirrel',
  'starfish',
  'stingray',
  'swan',
  'tapir',
  'tiger',
  'toad',
  'trout',
  'turkey',
  'turtle',
  'vulture',
  'walrus',
  'wasp',
  'weasel',
  'whale',
  'wolf',
  'wombat',
  'woodpecker',
  'worm',
  'wren',
  'yak',
  'zebra',
];

export const STYLES = [
  'anime',
  'fantasy',
  'dark fantasy',
  'abstract',
  'academic',
  'art deco',
  'art nouveau',
  'baroque',
  'bauhaus',
  'byzantine',
  'classicism',
  'conceptual art',
  'contemporary',
  'cubism',
  'dada',
  'digital art',
  'expressionism',
  'fauvism',
  'futurism',
  'gothic',
  'graffiti',
  'hyperrealism',
  'impressionism',
  'installation art',
  'land art',
  'minimalism',
  'modernism',
  'neo-classicism',
  'neo-expressionism',
  'op art',
  'performance art',
  'pop art',
  'post-impressionism',
  'postmodernism',
  'pre-raphaelite',
  'realism',
  'renaissance',
  'rococo',
  'romanticism',
  'surrealism',
  'symbolism',
  'video art',
];

export const JOBS = [
  'accountant',
  'actor',
  'actress',
  'administrator',
  'advertising executive',
  'aerospace engineer',
  'agricultural engineer',
  'air traffic controller',
  'airline pilot',
  'architect',
  'archivist',
  'artist',
  'astronomer',
  'athlete',
  'attorney',
  'author',
  'baker',
  'banker',
  'barber',
  'bartender',
  'biologist',
  'blacksmith',
  'botanist',
  'bricklayer',
  'bus driver',
  'business analyst',
  'butcher',
  'carpenter',
  'cashier',
  'chef',
  'chemical engineer',
  'chemist',
  'civil engineer',
  'cleaner',
  'clergy',
  'coach',
  'computer programmer',
  'construction worker',
  'consultant',
  'copywriter',
  'curator',
  'customer service representative',
  'dancer',
  'data analyst',
  'dental hygienist',
  'dentist',
  'designer',
  'detective',
  'dietitian',
  'doctor',
  'economist',
  'editor',
  'electrician',
  'engineer',
  'environmental scientist',
  'event planner',
  'farmer',
  'fashion designer',
  'film director',
  'firefighter',
  'fisherman',
  'florist',
  'geologist',
  'graphic designer',
  'hairdresser',
  'healthcare assistant',
  'historian',
  'hotel manager',
  'human resources manager',
  'interior designer',
  'journalist',
  'judge',
  'lawyer',
  'librarian',
  'lifeguard',
  'locksmith',
  'machinist',
  'magician',
  'makeup artist',
  'marketing manager',
  'massage therapist',
  'mechanic',
  'meteorologist',
  'microbiologist',
  'miner',
  'model',
  'musician',
  'nurse',
  'nutritionist',
  'occupational therapist',
  'optician',
  'painter',
  'paramedic',
  'paralegal',
  'park ranger',
  'pediatrician',
  'personal trainer',
  'pharmacist',
  'photographer',
  'physical therapist',
  'physicist',
  'pilot',
  'plumber',
  'police officer',
  'politician',
  'professor',
  'programmer',
  'psychologist',
  'public relations specialist',
  'real estate agent',
  'receptionist',
  'researcher',
  'salesperson',
  'scientist',
  'security guard',
  'singer',
  'social worker',
  'software engineer',
  'speech therapist',
  'surgeon',
  'taxi driver',
  'teacher',
  'technician',
  'therapist',
  'translator',
  'travel agent',
  'truck driver',
  'veterinarian',
  'videographer',
  'waiter',
  'waitress',
  'web developer',
  'welder',
  'writer',
  'zoologist',
];

export const CULTURES = [
  'american',
  'canadian',
  'mexican',
  'brazilian',
  'british',
  'french',
  'german',
  'italian',
  'spanish',
  'ukrainian',
  'chinese',
  'japanese',
  'indian',
  'south korean',
  'australian',
  'egyptian',
  'south african',
  'turkish',
  'saudi arabian',
  'iranian',
  'indonesian',
  'filipino',
  'vietnamese',
  'thai',
  'english',
  'ancient egyptian',
  'sumerian',
  'akkadian',
  'babylonian',
  'assyrian',
  'hittite',
  'phoenician',
  'ancient greek',
  'minoan',
  'mycenaean',
  'etruscan',
  'ancient roman',
  'celtic',
  'norse',
  'ancient chinese',
  'ancient indian',
  'persian',
  'byzantine',
  'inca',
  'maya',
  'aztec',
  'olmec',
  'ancient israelite',
];

export const PEOPLE = [
  'mom',
  'mother',
  'dad',
  'daddy',
  'father',
  'granny',
  'grandpa',
  'boy',
  'girl',
  'baby',
  'teenager',
  'man',
  'woman',
];

export const WORDS = [
  'World of Warcraft',
  'Dota',
  'Warcraft',
  'Dune',
  'Game of Thrones',
  'League of Legends',
  'Marvel',
  'Disney',
  'DC',
  'Star wars',
  'DnD',
  'The Elder Scrolls',
  'Warhammer',
  'Harry Potter',
  'A Song of Ice and Fire',
  'Middle-earth',
  'The Witcher',
  'Atlantis',
  'Neverland',
  'Azeroth',
  'Asgard',
  'Dinotopia',
  'Dreamland',
  'Rifts',
  'Wonderland',
];

type TYPES =
  | 'color'
  | 'body-part'
  | 'preposition'
  | 'job'
  | 'animal'
  | 'random-word'
  | 'style'
  | 'number'
  | 'cultures'
  | 'people'
  | 'words';
export const FLOWS: TYPES[][] = [
  ['people', 'job', 'preposition', 'cultures'],
  ['people', 'job', 'preposition', 'cultures', 'preposition', 'animal'],
  ['people', 'job', 'preposition', 'cultures', 'preposition', 'style'],
  ['people', 'job', 'preposition', 'cultures', 'preposition', 'animal', 'preposition', 'style'],
  ['people', 'preposition', 'cultures', 'preposition', 'animal'],
  ['people', 'preposition', 'animal'],
  ['people', 'preposition', 'cultures', 'preposition', 'animal', 'preposition', 'style'],
  ['people', 'preposition', 'animal', 'preposition', 'style'],
  ['people', 'job', 'preposition', 'cultures', 'preposition', 'words'],
  ['people', 'job', 'preposition', 'cultures', 'preposition', 'animal', 'preposition', 'words'],
  ['people', 'job', 'preposition', 'cultures', 'preposition', 'style', 'preposition', 'words'],
  ['people', 'job', 'preposition', 'cultures', 'preposition', 'animal', 'preposition', 'style', 'preposition', 'words'],
  ['people', 'preposition', 'cultures', 'preposition', 'animal', 'preposition', 'words'],
  ['people', 'preposition', 'animal', 'preposition', 'words'],
  ['people', 'preposition', 'cultures', 'preposition', 'animal', 'preposition', 'style', 'preposition', 'words'],
  ['people', 'preposition', 'animal', 'preposition', 'style', 'preposition', 'words'],
  ['color', 'body-part', 'preposition', 'job'],
  ['color', 'body-part', 'preposition', 'animal'],
  ['color', 'body-part', 'preposition', 'number', 'animal'],
  ['number', 'color', 'body-part', 'preposition', 'job'],
  ['number', 'color', 'body-part', 'preposition', 'animal'],
  ['number', 'color', 'body-part', 'preposition', 'number', 'animal'],
  ['color', 'animal', 'preposition', 'random-word'],
  ['animal', 'preposition', 'random-word'],
  ['color', 'animal', 'preposition', 'random-word', 'preposition', 'words'],
  ['animal', 'preposition', 'random-word', 'preposition', 'words'],
  ['color', 'animal', 'preposition', 'job'],
  ['color', 'animal', 'preposition', 'body-part'],
  ['color', 'animal', 'preposition', 'color', 'body-part'],
  ['color', 'animal', 'preposition', 'number', 'body-part'],
  ['color', 'animal', 'preposition', 'number', 'color', 'body-part'],
  ['animal', 'preposition', 'color', 'body-part'],
  ['number', 'animal', 'preposition', 'number', 'color', 'body-part'],
  ['animal', 'preposition', 'color', 'number', 'body-part'],
  ['number', 'animal', 'preposition', 'color', 'body-part'],
  ['job', 'preposition', 'animal'],
  ['job', 'preposition', 'color', 'animal'],
  ['job', 'number', 'preposition', 'animal'],
  ['job', 'number', 'preposition', 'color', 'animal'],
  ['job', 'preposition', 'animal', 'preposition', 'words'],
  ['job', 'preposition', 'color', 'animal', 'preposition', 'words'],
  ['job', 'preposition', 'color', 'body-part'],
  ['job', 'preposition', 'random-word'],
  ['color', 'body-part', 'preposition', 'job', 'preposition', 'style'],
  ['color', 'body-part', 'preposition', 'animal', 'preposition', 'style'],
  ['color', 'animal', 'preposition', 'random-word', 'preposition', 'style'],
  ['animal', 'preposition', 'random-word', 'preposition', 'style'],
  ['color', 'animal', 'preposition', 'job', 'preposition', 'style'],
  ['color', 'animal', 'preposition', 'body-part', 'preposition', 'style'],
  ['color', 'animal', 'preposition', 'color', 'body-part', 'preposition', 'style'],
  ['animal', 'preposition', 'color', 'body-part', 'preposition', 'style'],
  ['job', 'preposition', 'animal', 'preposition', 'style'],
  ['job', 'preposition', 'color', 'animal', 'preposition', 'style'],
  ['job', 'preposition', 'color', 'body-part', 'preposition', 'style'],
  ['job', 'preposition', 'random-word', 'preposition', 'style'],
  ['job', 'number', 'preposition', 'animal', 'preposition', 'style'],
  ['job', 'number', 'preposition', 'color', 'animal', 'preposition', 'style'],
  ['job', 'preposition', 'animal', 'preposition', 'words', 'preposition', 'style'],
  ['job', 'preposition', 'color', 'animal', 'preposition', 'words', 'preposition', 'style'],
  ['color', 'animal', 'preposition', 'number', 'body-part', 'preposition', 'style'],
  ['color', 'animal', 'preposition', 'number', 'color', 'body-part', 'preposition', 'style'],
  ['number', 'animal', 'preposition', 'number', 'color', 'body-part', 'preposition', 'style'],
  ['animal', 'preposition', 'color', 'number', 'body-part', 'preposition', 'style'],
  ['number', 'animal', 'preposition', 'color', 'body-part', 'preposition', 'style'],
  ['color', 'body-part', 'preposition', 'number', 'animal', 'preposition', 'style'],
  ['number', 'color', 'body-part', 'preposition', 'job', 'preposition', 'style'],
  ['number', 'color', 'body-part', 'preposition', 'animal', 'preposition', 'style'],
  ['number', 'color', 'body-part', 'preposition', 'number', 'animal', 'preposition', 'style'],
  ['number', 'people', 'preposition', 'animal'],
  ['people', 'preposition', 'number', 'animal'],
  ['number', 'people', 'preposition', 'number', 'animal'],
  ['people', 'preposition', 'cultures', 'preposition', 'animal', 'preposition', 'style'],
  ['people', 'preposition', 'cultures', 'preposition', 'number', 'animal', 'preposition', 'style'],
  ['people', 'preposition', 'animal', 'preposition', 'style'],
  ['people', 'preposition', 'number', 'animal', 'preposition', 'style'],
  ['color', 'body-part', 'preposition', 'animal'],
  ['color', 'body-part', 'preposition', 'number', 'animal'],
  ['people', 'preposition', 'number', 'animal', 'preposition', 'words'],
];

export const TYPE_MAP: Record<Exclude<TYPES, 'number'>, string[]> = {
  'body-part': BODY_PARTS,
  'random-word': RANDOM_WORDS,
  animal: ANIMALS,
  color: COLORS,
  job: JOBS,
  preposition: PREPOSITIONS,
  style: STYLES,
  people: PEOPLE,
  words: WORDS,
  cultures: CULTURES,
};
